development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myday_development
  pool: 5
  username: admin
  password: password
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myday_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: postgresql
  encoding: utf8
  database: myday_production
  pool: 5
  username: rasiel
  password: password
